wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/assets/wallpapers/ferrari-day.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/assets/wallpapers/ferrari-day.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/assets/wallpapers/ferrari-day.png
    fit_mode = cover
}